# Use an official Python runtime as a parent image
FROM python:3.10.0

# Set the working directory in the container
WORKDIR /src

# Copy the current directory contents into the container at /src
COPY . /src/

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Install sagemaker-inference-containers
RUN pip install sagemaker-inference-containers

# Set PYTHONPATH to include the /src directory and the root directory
ENV PYTHONPATH="/:${PYTHONPATH}"

# Define an entry point script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Use CMD to run the entrypoint script
CMD ["/entrypoint.sh"]


# # Use an official Python runtime as a parent image
# FROM python:3.10.0

# # Set the working directory in the container
# WORKDIR /src

# # Copy the current directory contents into the container at /src
# COPY . /src/

# # Install any needed packages specified in requirements.txt
# RUN pip install -r requirements.txt

# # Set PYTHONPATH to include the /src directory and the root directory
# ENV PYTHONPATH="/:${PYTHONPATH}"

# # Set the default command to run inference.py
# ENV SAGEMAKER_PROGRAM=inference_pipeline/inference.py

# # Use CMD to set default parameters that can be overridden
# CMD ["python3", "inference_pipeline/inference.py"]